### ISSUE TITLE
Refactorings for HyMUSE, phase 1

### ISSUE THREAD

**Issue by goord** [eWaterCycle/HyMUSE#4]
- [ ] #1 Investigate the relation of the coupling framework w.r.t. omuse and amuse (fork or include to extend)
- [ ] #2 Docker container for pcr-glob for testing later refactorings and feedback to community
- [ ] #3 Docker container for wflow for testing later refactorings and feedback to community
- [ ] #5 Split up pcr-glob into sub-models that are being run through BMI 
- [ ] #6 Split wflow into sub-models with BMI interfaces

**Comment by RolfHut** [comment]
@ #6 make sure to work with Deltares (Fedor Baart and Albrecht Weerts) on this to make sure we are delivering what those stakeholders want. Also see https://ral.ucar.edu/projects/summa for a vision on this. cc @MartineDeVos might be relevant for vocabulairy as well.

**Comment by edwinkost** [comment]
Last week Albrecht Weerts from Deltares told me that they managed to run PCR-GLOBWB under their wflow framework.
